"""
Simulation tick engine for ARES.

Advances the shared in-memory HabitatState by a configurable number of
simulated hours. All formulas here are intentionally simple, linear, and
deterministic — this is a prototype, not a physics engine. See the
docstring on `run_tick` for the exact formula.

No prediction, optimization, or randomness lives here.
"""

from app.models import HabitatState
from app.utils import clamp

# --- Facility effect constants (per simulated hour, at 100% allocation) ---
# These represent each facility's contribution beyond a module's own
# baseline resource demand. All values are illustrative for the prototype.
SOLAR_FARM_ENERGY_GENERATION = 40.0     # extra energy generated by solar_farm
WATER_RECYCLER_RECOVERY = 35.0          # extra water recovered by water_recycler
GREENHOUSE_OXYGEN_GENERATION = 6.0      # extra oxygen generated by greenhouse

# --- Astronaut "occupancy load" constants ---
# When an astronaut is physically located in a module, that module has to
# do extra work (life support, filtration, climate control) to support
# them. This is on top of the astronaut's own personal oxygen/water
# consumption, and scales with the astronaut's activity_multiplier.
OCCUPANCY_OXYGEN_LOAD_PER_ASTRONAUT = 0.3
OCCUPANCY_WATER_LOAD_PER_ASTRONAUT = 0.15
OCCUPANCY_ENERGY_LOAD_PER_ASTRONAUT = 0.5

# --- Status thresholds ---
# A resource is "warning" once it drops within 1.5x of its critical
# threshold, and "critical" once it's at or below that threshold.
WARNING_MULTIPLIER = 1.5


def _occupancy_loads(state: HabitatState) -> dict[str, dict[str, float]]:
    """
    Per-module, per-resource extra demand generated by astronauts who are
    currently located there. Returns {module_id: {"oxygen": x, "water": y, "energy": z}}.
    """
    loads: dict[str, dict[str, float]] = {
        module_id: {"oxygen": 0.0, "water": 0.0, "energy": 0.0} for module_id in state.modules
    }
    for astronaut in state.astronauts:
        module_id = astronaut.current_location
        if module_id not in loads:
            continue  # astronaut located somewhere outside tracked modules; ignore
        k = astronaut.activity_multiplier
        loads[module_id]["oxygen"] += OCCUPANCY_OXYGEN_LOAD_PER_ASTRONAUT * k
        loads[module_id]["water"] += OCCUPANCY_WATER_LOAD_PER_ASTRONAUT * k
        loads[module_id]["energy"] += OCCUPANCY_ENERGY_LOAD_PER_ASTRONAUT * k
    return loads


def _module_demand_totals(state: HabitatState) -> dict[str, float]:
    """
    Sum of every module's effective demand per resource, for one simulated
    hour. Effective demand = (module's base demand * its current allocation
    %) + any astronaut occupancy load in that module.
    """
    occupancy = _occupancy_loads(state)
    totals = {"oxygen": 0.0, "water": 0.0, "energy": 0.0}
    for module_id, module in state.modules.items():
        alloc = module.current_allocation
        demand = module.resource_demand
        occ = occupancy[module_id]
        totals["oxygen"] += demand.oxygen * (alloc.oxygen / 100.0) + occ["oxygen"]
        totals["water"] += demand.water * (alloc.water / 100.0) + occ["water"]
        totals["energy"] += demand.energy * (alloc.energy / 100.0) + occ["energy"]
    return totals


def _astronaut_demand_totals(state: HabitatState) -> dict[str, float]:
    """
    Direct personal consumption by the crew (breathing + drinking),
    scaled by each astronaut's activity_multiplier. Astronauts have no
    direct energy field, so energy is only affected via occupancy load.
    """
    oxygen = sum(a.oxygen_demand_per_hour * a.activity_multiplier for a in state.astronauts)
    water = sum((a.water_demand_per_day / 24.0) * a.activity_multiplier for a in state.astronauts)
    return {"oxygen": oxygen, "water": water, "energy": 0.0}


def _facility_generation_bonus(state: HabitatState) -> dict[str, float]:
    """
    Extra generation/recovery contributed by specific facility modules,
    scaled by that module's own current allocation percentage for the
    relevant resource (a facility running at reduced allocation performs
    less well).
    """
    bonus = {"oxygen": 0.0, "water": 0.0, "energy": 0.0}
    if "solar_farm" in state.modules:
        alloc_pct = state.modules["solar_farm"].current_allocation.energy / 100.0
        bonus["energy"] += SOLAR_FARM_ENERGY_GENERATION * alloc_pct
    if "water_recycler" in state.modules:
        alloc_pct = state.modules["water_recycler"].current_allocation.water / 100.0
        bonus["water"] += WATER_RECYCLER_RECOVERY * alloc_pct
    if "greenhouse" in state.modules:
        alloc_pct = state.modules["greenhouse"].current_allocation.oxygen / 100.0
        bonus["oxygen"] += GREENHOUSE_OXYGEN_GENERATION * alloc_pct
    return bonus


def _resource_status(resource) -> str:
    if resource.current_level <= resource.critical_threshold:
        return "critical"
    if resource.current_level <= resource.critical_threshold * WARNING_MULTIPLIER:
        return "warning"
    return "stable"


def _module_status(module) -> str:
    """
    A module is critical if any resource's current allocation has fallen
    below its minimum safe allocation, warning if it's within 10 points
    of that floor, otherwise stable.
    """
    pairs = [
        (module.current_allocation.oxygen, module.minimum_safe_allocation.oxygen),
        (module.current_allocation.water, module.minimum_safe_allocation.water),
        (module.current_allocation.energy, module.minimum_safe_allocation.energy),
    ]
    if any(current < minimum for current, minimum in pairs):
        return "critical"
    if any(current < minimum + 10.0 for current, minimum in pairs):
        return "warning"
    return "stable"


def run_tick(state: HabitatState, simulated_hours: float = 1.0) -> tuple[HabitatState, dict[str, float], list[str]]:
    """
    Advance `state` in place by `simulated_hours` and return
    (state, resource_deltas, status_changes).

    FORMULA (per resource, per simulated hour):
        generation  = resource.generation_rate + facility_bonus[resource]
        consumption = resource.base_consumption_rate
                      + module_demand_total[resource]   (module base demand * allocation % + astronaut occupancy load)
                      + astronaut_demand_total[resource] (direct crew breathing/drinking, scaled by activity)
        net_change_per_hour = generation - consumption
        new_level = clamp(current_level + net_change_per_hour * simulated_hours, 0, max_capacity)

    Facility bonuses (on top of the baseline generation_rate):
        - solar_farm boosts energy generation, scaled by its own energy allocation %
        - water_recycler boosts water recovery, scaled by its own water allocation %
        - greenhouse boosts oxygen generation, scaled by its own oxygen allocation %

    Astronaut location matters twice:
        1. Personal demand (oxygen/water) is always charged regardless of location.
        2. An extra "occupancy load" is added to whichever module the astronaut is
           currently in, representing the added life-support burden of hosting them.
    """
    facility_bonus = _facility_generation_bonus(state)
    module_demand = _module_demand_totals(state)
    astronaut_demand = _astronaut_demand_totals(state)

    resource_deltas: dict[str, float] = {}
    status_changes: list[str] = []

    for resource_name, resource in state.resources.items():
        generation = resource.generation_rate + facility_bonus[resource_name]
        consumption = (
            resource.base_consumption_rate
            + module_demand[resource_name]
            + astronaut_demand[resource_name]
        )
        net_per_hour = generation - consumption
        previous_level = resource.current_level
        previous_status = _resource_status(resource)

        new_level = clamp(
            previous_level + net_per_hour * simulated_hours,
            0.0,
            resource.max_capacity,
        )
        resource.current_level = new_level
        resource_deltas[resource_name] = new_level - previous_level

        new_status = _resource_status(resource)
        if new_status != previous_status:
            status_changes.append(
                f"Resource '{resource_name}' status changed: {previous_status} -> {new_status}"
            )

    # Module statuses are derived from allocation vs. minimum-safe allocation.
    # The tick engine does not change allocations itself (that's future
    # optimization logic's job) — it just re-evaluates status given current values.
    for module_id, module in state.modules.items():
        previous_status = module.status
        new_status = _module_status(module)
        module.status = new_status
        if new_status != previous_status:
            status_changes.append(
                f"Module '{module_id}' status changed: {previous_status} -> {new_status}"
            )

    state.simulation.tick_count += 1
    state.simulation.elapsed_simulated_hours += simulated_hours

    return state, resource_deltas, status_changes